from enum import Enum


class ToolStatus(str, Enum):
    REGISTERED = "REGISTERED"
    INITIALIZED = "INITIALIZED"
    READY = "READY"
    VALIDATING = "VALIDATING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    CANCELLED = "CANCELLED"
    CLEANUP = "CLEANUP"
    DISPOSED = "DISPOSED"


class ToolCategory(str, Enum):
    BROWSER = "BROWSER"
    PYTHON = "PYTHON"
    FILESYSTEM = "FILESYSTEM"
    SEARCH = "SEARCH"
    UTILITY = "UTILITY"
    EXTERNAL_API = "EXTERNAL_API"
    DATABASE = "DATABASE"
    COMMUNICATION = "COMMUNICATION"


class PermissionLevel(str, Enum):
    SAFE = "SAFE"
    USER_CONFIRMATION_REQUIRED = "USER_CONFIRMATION_REQUIRED"
    ADMIN_ONLY = "ADMIN_ONLY"
    BLOCKED = "BLOCKED"


class ExecutionMode(str, Enum):
    LOCAL = "LOCAL"
    SANDBOXED = "SANDBOXED"
    REMOTE = "REMOTE"


class ToolCapability(str, Enum):
    READ_FILE = "READ_FILE"
    WRITE_FILE = "WRITE_FILE"
    SEARCH_WEB = "SEARCH_WEB"
    EXECUTE_CODE = "EXECUTE_CODE"
    ANALYZE_IMAGE = "ANALYZE_IMAGE"
    OCR = "OCR"
    SPEECH = "SPEECH"
    DATABASE = "DATABASE"
    DOWNLOAD_FILE = "DOWNLOAD_FILE"
    SCREENSHOT = "SCREENSHOT"
