"""add_branching_and_versions

Revision ID: 031744e327ea
Revises: 01d5de63e1ff
Create Date: 2026-07-11 13:15:05.377966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031744e327ea'
down_revision: Union[str, Sequence[str], None] = '01d5de63e1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('parent_conversation_id', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('branch_name', sa.String(length=100), nullable=True))
    op.add_column('conversations', sa.Column('branch_depth', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'conversations', 'conversations', ['parent_conversation_id'], ['id'], ondelete='SET NULL')
    op.add_column('messages', sa.Column('parent_message_id', sa.Uuid(), nullable=True))
    op.add_column('messages', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_messages_is_active'), 'messages', ['is_active'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'], ondelete='SET NULL')
    
    op.create_table('message_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_message_feedback_id'), 'message_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_feedback_id'), table_name='message_feedback')
    op.drop_table('message_feedback')
    
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_is_active'), table_name='messages')
    op.drop_column('messages', 'is_active')
    op.drop_column('messages', 'version')
    op.drop_column('messages', 'parent_message_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'branch_depth')
    op.drop_column('conversations', 'branch_name')
    op.drop_column('conversations', 'parent_conversation_id')
    # ### end Alembic commands ###
