"""add_plan_versioning_and_dependencies

Revision ID: 6e92b30ce523
Revises: 97fb553d007e
Create Date: 2026-07-12 16:00:28.518420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e92b30ce523'
down_revision: Union[str, Sequence[str], None] = '97fb553d007e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_steps', sa.Column('depends_on', sa.JSON(), nullable=True))
    op.add_column('plans', sa.Column('plan_version', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('is_latest', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('parent_plan_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'plans', 'plans', ['parent_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_column('plans', 'parent_plan_id')
    op.drop_column('plans', 'is_latest')
    op.drop_column('plans', 'plan_version')
    op.drop_column('plan_steps', 'depends_on')
    # ### end Alembic commands ###
